from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('search/', views.search, name='search'),
    path('search/autocomplete/', views.search_autocomplete, name='search_autocomplete'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/review/', views.add_review, name='add_review'),
    path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('products/', views.product_list, name='product_list'),
    path('checkout/', views.checkout, name='checkout'),
    path('create-payment/', views.create_payment, name='create_payment'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-failed/', views.payment_failed, name='payment_failed'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('return/<int:order_id>/', views.request_return, name='request_return'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change-password/', views.change_password, name='change_password'),
    path('order/track/<int:order_id>/', views.order_tracking, name='order_tracking'),
    
    # Store/Order Helpers
    path('order/<int:order_id>/invoice/', views.download_invoice, name='download_invoice'),
    path('order/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/', views.remove_coupon, name='remove_coupon'),
    
    # Notifications
    path('notifications/', views.notifications_view, name='notifications_view'),
    path('notifications/read-all/', views.mark_all_read, name='mark_all_read'),
    path('notifications/read/<int:notif_id>/', views.mark_as_read, name='mark_as_read'),
    
    path('notify/<int:product_id>/', views.notify_me, name='notify_me'),
    path('product/<int:product_id>/question/', views.ask_question, name='ask_question'),
    path('question/<int:question_id>/answer/', views.answer_question, name='answer_question'),
    path('question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('newsletter/unsubscribe/<str:email>/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('login/', views.user_login, name='login'),
    path('verify-2fa/', views.verify_2fa, name='verify_2fa'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('push/subscribe/', views.save_push_subscription, name='save_push_subscription'),
    path('order/<int:order_id>/status/', views.order_status_api, name='order_status_api'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact_us'),
    path('info/<slug:slug>/', views.info_page, name='info_page'),
    path('chatbot/query/', views.chatbot_query, name='chatbot_query'),
    path('chatbot/clear/', views.clear_chatbot_history, name='clear_chatbot_history'),
    path('chatbot/ticket/', views.create_support_ticket, name='create_support_ticket'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='shop/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='shop/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='shop/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='shop/password_reset_complete.html'), name='password_reset_complete'),

    # OTP Login
    path('send-otp/', views.send_otp, name='send_otp'),
    path('otp-login/', views.otp_login, name='otp_login'),

    # AI Chatbot Enhanced APIs
    path('api/orders/<int:order_id>/status/', views.order_status_api, name='order_status_api_v2'),
    path('api/orders/my-orders/', views.my_orders_api, name='my_orders_api'),
    path('api/orders/verify/', views.verify_order_api, name='verify_order_api'),
    path('api/products/search/', views.product_search_api, name='product_search_api'),
    path('api/offers/active/', views.active_offers_api, name='active_offers_api'),
    path('api/returns/<int:order_id>/', views.return_status_api, name='return_status_api'),
    path('api/returns/create/', views.create_return_api, name='create_return_api'),
    path('api/chat/log/', views.log_chat_api, name='log_chat_api'),
]