# Generated by Django 6.0.4 on 2026-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
