# Generated by Django 6.0.4 on 2026-04-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_category_slug_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
