# Generated by Django 6.0.4 on 2026-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_faq_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
