# Generated by Django 6.0.4 on 2026-05-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_chatmessage_sentiment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sentiment_score',
        ),
    ]
