"""
Django settings for online_shop project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import urllib.parse
load_dotenv()


# --------------------------------------------------
# Base Directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Security Settings
# --------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost 127.0.0.1 online-shop-w8q3.onrender.com').split()

# --------------------------------------------------
# Application Definition
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  
    'cloudinary_storage',           
    'cloudinary',
    'django.contrib.sitemaps',
    'progressive',
    'shop',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'online_shop.urls'

TEMPLATES = [
    {
         'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'shop' / 'templates'], 
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_data',
                'shop.context_processors.vapid_key',
                'shop.context_processors.social_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgres://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME')}",
        conn_max_age=600
    )
}

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# --------------------------------------------------
# Password Validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'   # ✅ Better for India

USE_I18N = True
USE_TZ = True
# settings.py


# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --------------------------------------------------
# Static Files (CSS, JS)
# --------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'shop' / 'static']


# --------------------------------------------------
# Media Files (User Uploads)
# --------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --------------------------------------------------
# Default Primary Key
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True 
# <-- Your Gmail 
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD =os.getenv('EMAIL_HOST_PASSWORD') 
DEFAULT_FROM_EMAIL = 'santhoshkumarv09042005@gmail.com' # Payment 
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID') 
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET') # உன் secret போடு # Shipping 
FREE_SHIPPING_THRESHOLD = 500 # ₹500 above = free shipping 
SHIPPING_CHARGE = 49 # below ₹500 = ₹49 # Returns
RETURN_WINDOW_DAYS = 7 # 7 days return window # Twilio Settings 


PROGRESSIVE_APP_NAME = 'Online Shop'
PROGRESSIVE_APP_THEME_COLOR = '#000000'
PROGRESSIVE_APP_DISPLAY = 'standalone'
PROGRESSIVE_APP_START_URL = '/'
PROGRESSIVE_APP_ICONS = [{'src': '/static/images/logo.png', 'sizes': '160x160'}]
PROGRESSIVE_SERVICE_WORKER_PATH = BASE_DIR / 'static/js/serviceworker.js'

APPEND_SLASH = False

VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY')


CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8001',
    'http://localhost:8001',
    'https://online-shop-w8q3.onrender.com',
]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'


# Social Media Links
SOCIAL_LINKS = {
    'instagram': 'https://www.instagram.com/sanzcart',
    'twitter': 'https://twitter.com/sanzcart',
    'facebook': 'https://www.facebook.com/sanzcart',
    'pinterest': 'https://www.pinterest.com/sanzcart',
}
